#设置访问信息
server:
  port: 2016
  context-path: /redpro-oaas
  
  
spring:  
#配置项目名 eureka需要用
  application:
      name: redpro-oaas
      
#定义此处含有application-*.yml的字段回覆盖本文件
  profiles:
    active: testEnv
#视图定义
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
#配置数据
  jpa:
    database:
      oracle
  datasource:
    url: jdbc:oracle:thin:@10.45.54.177:1521/ORCL
    username: cloud_iom
    password: cloud_iom
    driver-class-name: oracle.jdbc.OracleDriver
    driverClassName: oracle.jdbc.OracleDriver
    tomcat:
      max-active: 10
      maxActive: 10

#redis配置
  redis:
    database: 1 #索引（默认为0）
    #host: 127.0.0.1 #地址
    host: 10.128.90.37
    port: 6379 #端口号
    #password:  #连接密码（默认空）
    password: ljx
    pool:
      max-idle: 8 #连接池中的最大空闲连接
      min-idle: 0 #连接池中的最小空闲连接
      max-active: 8 #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout: 0 #连接超时时间（毫秒）
    
#可以定义常量
yongzhi:
  name: yyy
  birthday: 1992年5月
  show: BLESS GOD
  
today: ${yongzhi.show} , I need help

#eureka 注册
eureka:
  instance:
       leaseRenewalIntervalInSeconds: 30   #心跳时间,默认是30秒，不能大于leaseExpirationDurationInSeconds       #此配置建议只试用开发和测试环境
       leaseExpirationDurationInSeconds: 90 #发呆时间, 最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了，默认是90秒 #此配置建议只试用开发和测试环境
       preferIpAddress: true    #设为true使用IP注册，默认是使用hostname注册调用时可能无法识别主机名
       instanceId: ${spring.cloud.client.ipAddress}:${spring.application.name}:${server.port}  #注册实例ID生成规则
       statusPageUrlPath: ${server.context-path}/info   #服务信息地址生成规则 即Status的点击地址
       healthCheckUrlPath: ${server.context-path}/health  #健康检测地址生成规则
  client:
    service-url:
      defaultZone: http://127.0.0.1:2017/eureka/

#日志配置 spring boot 内置 logback 可以在此配置 也可以指定xml来配置
logging:
  config: classpath:log/logback.xml
  path: D:/home/${server.context-path}
